name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master # EXACTLY @master

      - name: Setup Node.js
        uses: actions/setup-node@master # EXACTLY @master
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Clean dist directory
        run: rm -rf dist/*

      - name: Build project
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          CUSTOM_SEARCH_ENGINE_ID: ${{ secrets.CUSTOM_SEARCH_ENGINE_ID }}
        run: node build.js

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@master # EXACTLY @master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish: dist

      - name: Verify deployment
        run: |
          curl -sSL https://github.jishnukarri.me/model-new/model.json
          curl -sSL https://github.jishnukarri.me/images.json
          echo "Deployment verified"